blueprint:
  name: Charger State Tracker
  description: |
    Track the state of battery chargers (Idle, Charging, Complete) based on power consumption.
    
    This blueprint monitors a power sensor and automatically transitions through states:
    - Idle: No charging activity (power below threshold)
    - Charging: Active charging detected (power above threshold)
    - Complete: Charging finished (power dropped below threshold after charging)
    
    Requires an input_select helper to be created first with options: Idle, Charging, Complete
  domain: automation
  input:
    power_sensor:
      name: Power Consumption Sensor
      description: The sensor that measures power consumption (in Watts)
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: power
    status_input_select:
      name: Status Helper
      description: Input select helper to store the charger status (must have options: Idle, Charging, Complete)
      selector:
        entity:
          filter:
            - domain: input_select
    power_threshold:
      name: Power Threshold
      description: Power level (in Watts) that indicates charging is active
      default: 4
      selector:
        number:
          min: 0.5
          max: 100
          step: 0.5
          unit_of_measurement: "W"
          mode: slider
    charging_start_delay:
      name: Charging Start Delay
      description: How long power must be above threshold before marking as "Charging" (debounce)
      default: 5
      selector:
        number:
          min: 1
          max: 60
          step: 1
          unit_of_measurement: "seconds"
          mode: slider
    charging_complete_delay:
      name: Charging Complete Delay
      description: How long power must be below threshold before marking as "Complete"
      default: 30
      selector:
        number:
          min: 5
          max: 300
          step: 5
          unit_of_measurement: "seconds"
          mode: slider
    idle_reset_delay:
      name: Idle Reset Delay
      description: How long to stay in "Complete" state before resetting to "Idle"
      default: 300
      selector:
        number:
          min: 60
          max: 3600
          step: 60
          unit_of_measurement: "seconds"
          mode: slider
    enable_notifications:
      name: Enable Notifications
      description: Send notifications when charging completes
      default: false
      selector:
        boolean:
    notification_service:
      name: Notification Service
      description: The notification service to use (only used if notifications enabled)
      default: ""
      selector:
        text:
    notification_title:
      name: Notification Title
      description: Title for the notification
      default: "Charging Complete"
      selector:
        text:
    notification_message:
      name: Notification Message
      description: Message for the notification
      default: "Battery chargers have finished charging"
      selector:
        text:

mode: queued
max_exceeded: silent

trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    above: !input power_threshold
    for:
      seconds: !input charging_start_delay
    id: charging_started
  
  - platform: numeric_state
    entity_id: !input power_sensor
    below: !input power_threshold
    for:
      seconds: !input charging_complete_delay
    id: charging_complete
  
  - platform: state
    entity_id: !input status_input_select
    to: 'Complete'
    for:
      seconds: !input idle_reset_delay
    id: reset_to_idle

action:
  - choose:
      # Charging Started
      - conditions:
          - condition: trigger
            id: charging_started
          - condition: state
            entity_id: !input status_input_select
            state: 'Idle'
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input status_input_select
            data:
              option: "Charging"
      
      # Charging Complete
      - conditions:
          - condition: trigger
            id: charging_complete
          - condition: state
            entity_id: !input status_input_select
            state: 'Charging'
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input status_input_select
            data:
              option: "Complete"
          
          # Send notification if enabled
          - if:
              - condition: template
                value_template: "{{ enable_notifications }}"
              - condition: template
                value_template: "{{ notification_service != '' }}"
            then:
              - service: "{{ notification_service }}"
                data:
                  title: !input notification_title
                  message: !input notification_message
      
      # Reset to Idle
      - conditions:
          - condition: trigger
            id: reset_to_idle
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input status_input_select
            data:
              option: "Idle"
